config/routes.rb
Rails.application.routes.draw do
  devise_for :landlords, controllers: {registrations: 'registrations'}
  devise_for :tenants, controllers: {registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  get 'home/index'
  root to: "home#index"

  resources :tenants do
    resources :service_requests, controller: 'tenant_service_request'
    resources :service_request_comments, only: [:create, :edit, :destroy]
  end

  resources :landlords do
    resources :service_requests, controller: 'landlord_service_request'
    resources :service_request_comments, only: [:create, :edit, :destroy]
  end

  resources :properties

  resources :payments do
    member do
      get :index
    end
  end
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  include User

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  belongs_to :account
  belongs_to :property
  has_many :service_requests
  has_many :service_request_comments, as: :commentable
  accepts_nested_attributes_for :account

  def self.find_for_facebook_oauth(auth)
    user = Tenant.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = Tenant.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        account = Account.create(
          first_name: auth.extra.raw_info.first_name,
          last_name: auth.extra.raw_info.last_name
        )
        Tenant.create(account:    account,
                      provider:   auth.provider,
                      uid:        auth.uid,
                      email:      auth.info.email,
                      photo_url:  auth.info.image,
                      password: Devise.friendly_token[0, 20])
      end
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      allow = [:email, :password, :password_confirmation, :unit, :property_id, account_attributes: [:first_name, :last_name, :street, :city, :state, :zip]]
      params[:tenant].permit(allow)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.haml
= form_for @tenant do |f|
  - if @tenant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tenant.errors.count, "error")} prohibited this tenant from being saved:"
      %ul
        - @tenant.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true
  %div
    = f.label :property
    = f.collection_select(:property_id, Property.all, :id, :name, prompt: 'Select a property')
  %div
    = f.label :unit
    %br/
    = f.text_field :unit
  = f.fields_for :account do |a|
    %div
      = a.label :first_name
      %br/
      = a.text_field :first_name
    %div
      = a.label :last_name
      %br/
      = a.text_field :last_name
    %div
      = a.label :street
      %br/
      = a.text_field :street
    %div
      = a.label :city
      %br/
      = a.text_field :city
    %div
      = a.select(:state, Rails.configuration.states)

  .actions
    = f.submit 'Save'

app/views/tenants/edit.html.haml
%h1
  = "Editing tenant #{@tenant.account.full_name}"

= render 'form'

= link_to 'Show', @tenant
\|
= link_to 'Back', tenants_path

app/views/tenants/index.html.haml
%h2 Listing tenants

%table.table-striped.table-bordered.table-condensed
  %tr
    %th
    %th Name
    %th Email
    %th Landlord
    %th Address
    %th Unit
    %th
    %th
    %th

  - @tenants.each do |tenant|
    %tr
      %td= image_tag(tenant.photo_url)
      %td= "#{tenant.account.last_name}, #{tenant.account.first_name}"
      %td= tenant.email
      %td= tenant.property ? tenant.property.landlord.email : ''
      %td= "#{tenant.account.street}, #{tenant.account.city}, #{tenant.account.state}"
      %td= tenant.unit
      %td= link_to 'Show', tenant
      %td= link_to 'Edit', edit_tenant_path(tenant)
      %td= link_to 'Destroy', tenant, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tenant', new_tenant_path

app/views/tenants/new.html.haml
%h1 New tenant

= render 'form'

= link_to 'Back', tenants_path

app/views/tenants/show.html.haml
= link_to 'Edit', edit_tenant_path(@tenant)
\|
= link_to 'Back', tenants_path