config/routes.rb
Rails.application.routes.draw do
  devise_for :landlords, controllers: {registrations: 'registrations'}
  devise_for :tenants, controllers: {registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  get 'home/index'
  root to: "home#index"

  resources :tenants do
    resources :service_requests, controller: 'tenant_service_request'
    resources :service_request_comments, only: [:create, :edit, :destroy]
  end

  resources :landlords do
    resources :service_requests, controller: 'landlord_service_request'
    resources :service_request_comments, only: [:create, :edit, :destroy]
  end

  resources :properties

  resources :payments do
    member do
      get :index
    end
  end
end

app/models/service_request.rb
class ServiceRequest < ActiveRecord::Base
  extend Enumerize

  belongs_to :tenant
  belongs_to :property
  has_many :comments, class_name: "ServiceRequestComment"

  enumerize :status, in: [:new, :in_progress, :resolved], default: :new

end

app/controllers/service_requests_controller.rb
class ServiceRequestsController < ApplicationController
  before_action :set_service_request, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user

  # GET /service_requests/1
  # GET /service_requests/1.json
  def show
  end

  # GET /service_requests/1/edit
  def edit
    @comment = ServiceRequestComment.new
  end

  # DELETE /service_requests/1
  # DELETE /service_requests/1.json
  def destroy
    ServiceRequestsMailer.send_delete_service_request_email(@service_request, current_user.full_name, app_base_url).deliver
    @service_request.destroy
    respond_to do |format|
      format.html { redirect_to service_requests_url, notice: 'Service request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service_request
    @service_request = ServiceRequest.find(params[:id])
  end

  def set_current_user
    # subclasses must override
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_request_params
    params.require(:service_request).permit([:content, :status, :tenant_id])
  end
end

app/helpers/service_requests_helper.rb
module ServiceRequestsHelper
end

app/views/service_requests/_comment_form.html.haml
%p
%h2 Comments
%table.table-striped.table-bordered.table-condensed
  %tr
    %th Date
    %th User
    %th Content
  - @service_request.comments.each do |comment|
    %tr
      %td= comment.created_at
      %td= comment.commentable.email
      %td= comment.content

- if current_tenant
  - path = tenant_service_request_comments_path(user_id: current_tenant.id)
- elsif current_landlord
  - path = landlord_service_request_comments_path(user_id: current_landlord.id)

%h1 Add a comment

= form_for @comment, url: path do |f|
  %div
    = f.text_area :content, autofocus: true, rows: 10, cols: 80, class: 'span8'
    = f.hidden_field :service_request_id, value: @service_request.id
  .actions
    = f.submit 'Save'

app/views/service_requests/_form.html.haml
%h3= "Property: #{@service_request.property.name}"

- if current_tenant
  = render partial: 'tenant_form'

- elsif current_landlord
  = render partial: 'landlord_form'

app/views/service_requests/_landlord_form.html.haml
= form_for @service_request, url: landlord_service_request_path(landlord_id: current_landlord.id) do |f|
  - if @service_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service_request.errors.count, "error")} prohibited this service_request from being saved:"
      %ul
        - @service_request.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :status
    = f.select :status, ServiceRequest.status.options
  %div
    %br/
    = f.text_area :content, disabled: true, rows: 10, cols: 80, class: "span8"
  .actions
    = f.submit 'Save'

app/views/service_requests/_tenant_form.html.haml
= form_for @service_request, url: tenant_service_requests_path(id: current_tenant.id) do |f|
  - if @service_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service_request.errors.count, "error")} prohibited this service_request from being saved:"
      %ul
        - @service_request.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :status
    = f.select :status, ServiceRequest.status.options
  %div
    %br/
    = f.text_area :content, autofocus: true, rows: 10, cols: 80, class: "span8"
  .actions
    = f.submit 'Save'

app/views/service_requests/edit.html.haml
%h1 Editing Service Request

= render 'form'

= render 'comment_form'

app/views/service_requests/index.html.haml
%h2= "Listing service requests for #{current_user.full_name}"

%table.table-striped.table-bordered.table-condensed
  %tr
    %th Date submitted
    %th Status
    %th Submitted by
    %th Property
    %th Landlord
    %th Content
    %th
    %th
    %th

  - @service_requests.each do |service_request|
    %tr
      %td= service_request.created_at.to_formatted_s(:short)
      %td= service_request.status.text
      %td= service_request.tenant ? service_request.tenant.email : ''
      %td= service_request.tenant ? service_request.tenant.property.name : ''
      %td= service_request.tenant ? service_request.tenant.property.landlord.email : ''
      %td= truncate(service_request.content, length: 30)
      - if current_landlord
        %td= link_to 'Reply', edit_landlord_service_request_path(id: service_request.id)
      - if current_tenant
        %td= link_to 'Show', tenant_service_request_path(id: service_request.id)
        %td= link_to 'Edit', edit_tenant_service_request_path(id: service_request.id)
        %td= link_to 'Delete', tenant_service_request_path(id: service_request.id), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

- if current_tenant && current_tenant.property.present?
  = link_to "New Service request for #{current_tenant.property.name}, Unit #{current_tenant.unit}", new_tenant_service_request_path

app/views/service_requests/new.html.haml
%h2 New Service Request

= render 'form'

= link_to 'Back', tenant_service_requests_path  # TODO: link to the correct resource

app/views/service_requests/show.html.haml
%h2 Service Issue Details
%table.table-bordered.table-condensed
  %tr
    %th.text-left Date Created
    %th.text-left Content
    %th.text-left Status
    %th.text-left Name
    %th
  %tr
    %td= @service_request.created_at.to_s format: :long
    %td= @service_request.content
    %td= @service_request.status_text
    %td= @service_request.tenant.full_name
    - if current_tenant
      %td= link_to 'Edit', edit_tenant_service_request_path(@current_tenant, @service_request)
    - elsif current_landlord
      %td= link_to 'Edit', edit_landlord_service_request_path(@current_landlord, @service_request)
%br
%h2 Comments
%table.table-bordered.table-condensed
  %tr
    %th.text-left Date Created
    %th.text-left Comment
    %th.text-left Name
  - if @service_request.comments
    - @service_request.comments.each do |comment|
      %tr
        %td.text-left= comment.created_at.to_s format: :long
        %td.text-left= comment.content
        %td.text-left= comment.commentable.full_name

%br
- if current_tenant
  = link_to 'Back', tenant_service_requests_path
- elsif current_landlord
  = link_to 'Back', landlord_service_requests_path