config/routes.rb
Rails.application.routes.draw do
  devise_for :landlords, controllers: {registrations: 'registrations'}
  devise_for :tenants, controllers: {registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }

  get 'home/index'
  root to: "home#index"

  resources :tenants do
    resources :service_requests, controller: 'tenant_service_request'
    resources :service_request_comments, only: [:create, :edit, :destroy]
  end

  resources :landlords do
    resources :service_requests, controller: 'landlord_service_request'
    resources :service_request_comments, only: [:create, :edit, :destroy]
  end

  resources :properties

  resources :payments do
    member do
      get :index
    end
  end
end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  include User

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :account
  accepts_nested_attributes_for :account
  has_many :tenants
  has_many :properties
  has_many :service_request_comments, as: :commentable
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: 'Landlord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params[:landlord]
    end
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/views/landlords/_form.html.haml
= form_for @landlord do |f|
  - if @landlord.errors.any?
    #error_explanation
      %h2= "#{pluralize(@landlord.errors.count, "error")} prohibited this landlord from being saved:"
      %ul
        - @landlord.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true
  = f.fields_for :account do |a|
    %div
      = a.label :first_name
      %br/
      = a.text_field :first_name
    %div
      = a.label :last_name
      %br/
      = a.text_field :last_name
    %div
      = a.label :street
      %br/
      = a.text_field :street
    %div
      = a.label :city
      %br/
      = a.text_field :city
    %div
      = a.select(:state, Rails.configuration.states)

  .actions
    = f.submit 'Save'

app/views/landlords/edit.html.haml
%h1 Editing landlord

= render 'form'

= link_to 'Show', @landlord
\|
= link_to 'Back', landlords_path

app/views/landlords/index.html.haml
%h2 Listing landlords

%table.table-striped.table-bordered.table-condensed
  %tr
    %th Name
    %th Email
    %th Address
    %th
    %th
    %th

  - @landlords.each do |landlord|
    %tr
      %td= "#{landlord.account.last_name}, #{landlord.account.first_name}"
      %td= landlord.email
      %td= "#{landlord.account.street}, #{landlord.account.city}, #{landlord.account.state}"
      %td= link_to 'Show', landlord
      %td= link_to 'Edit', edit_landlord_path(landlord)
      %td= link_to 'Destroy', landlord, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Landlord', new_landlord_path

app/views/landlords/new.html.haml
%h1 New landlord

= render 'form'

= link_to 'Back', landlords_path

app/views/landlords/show.html.haml
= link_to 'Edit', edit_landlord_path(@landlord)
\|
= link_to 'Back', landlords_path